### ISSUE TITLE
Finetuning of the fingerprint model

### ISSUE THREAD

**Issue by JustABiologist** [rxn4chemistry/rxnfp#13]
Hello dear team,
First of all, thanks for publishing this great resource! It really is amazing what you can do nowadays with transformers!

My question would be if there is a way to finetune the weights of your fingerprint model on a subset of reactions, to improve predictions for niche datasets. I saw the pretrained model being loaded in the tutorial https://rxn4chemistry.github.io/rxnfp/generate_fingerprints/ and wondered if it is possible to finetune it!

Thanks for your help in advance!

Greetings from germany!

**Comment by pschwllr** [comment]
Hi, thanks for your interest! 

For finetuning our fingerprint models best use the following notebook as an inspiration:
https://github.com/rxn4chemistry/rxnfp/blob/master/nbs/09_fine_tune_bert_on_uspto_1k_tpl.ipynb
