### ISSUE TITLE
Can't get USPTO 1k TPL dataset

### ISSUE THREAD

**Issue by lry124** [rxn4chemistry/rxnfp#14]
I can't get the uspto_1k_TPL data set for fine tune classification  from IBM Box.
The error message is:  This shared file or folder link has been removed or is unavailable to you.
And in you code the data was read from:
../data/uspto_1k_TPL/data_set/uspto_1k_TPL_train_valid.tsv.gzip

**Comment by avaucher** [comment]
Thanks for reporting this! The data should be available again on Box.
