### ISSUE TITLE
reactionid to reactioncode or name

### ISSUE THREAD

**Issue by thegodone** [rxn4chemistry/rxnfp#16]
I see that you have around 1000 reactionids but you provide only the first 50 one. can we have the full mapping between reactionid / reactiontemplate and reaction code / reaction name please

**Comment by pschwllr** [comment]
The mapping should be here: https://github.com/rxn4chemistry/rxnfp/blob/master/data/uspto_1k_TPL/individual_files/label_template.json

Is this what you were looking for?

**Comment by thegodone** [comment]
In fact, I saw this file already. 

I am looking for the name mapping to your mapping so "diels-alder ..." / "7.3…" is equal to your class "123..." from your label template file. 
You give only this mapping for the first 50 id in data/rxnclass2id.json & data/rxnclass2name.json used for reporting confusion matrice results. 
Is it possible to get the full mapping so fullrxnclass2id / name.json?

BR

Guillaume

**Comment by pschwllr** [comment]
I think that what confuses you is that we made experiments on multiple datasets. 

There is the dataset by Schneider et al. that contains 50 classes with 1000 reactions per class (https://github.com/rxn4chemistry/rxnfp/blob/master/data/schneider50k.tsv), those can be mapped using https://github.com/rxn4chemistry/rxnfp/blob/master/data/rxnclass2name.json
and 
https://github.com/rxn4chemistry/rxnfp/blob/master/data/rxnclass2id.json
this corresponds to the experiments in:
https://rxn4chemistry.github.io/rxnfp/results_classification_50k/.

Then we have published a new larger 1k TPL classification dataset that contains the 1000 most frequent reaction templates in the USPTO dataset (atom-mapping from RXNMapper). 

The labels for this dataset are: https://github.com/rxn4chemistry/rxnfp/blob/master/data/uspto_1k_TPL/individual_files/label_template.json

They are also visualised in:
https://rxn4chemistry.github.io/rxnfp/label_template_visualisation/

The full mapping fullrxnclass2id / name.json that you would like to have, you could get by extracting it from NextMove Software reactions and retraining a model.

I hope this helps. 

BR

Philippe

**Comment by thegodone** [comment]
thanks now I have the large dataset to get the names.

**Comment by biotech7** [comment]
@thegodone 
Would you please share the rest of 950 reaction names(as well as mapping ids). I'd like to train a full-rxn-name predictable model based on this project. 
Thanks!

**Comment by HanbumKo** [comment]
Hello, would you happen to have the fullrxnclass2id / name.json files organized for the USPTO_1k_TPL dataset? I’m fairly new to this field of research, so even after looking at the reaction templates below, I’m not entirely sure how to map them to named reactions (e.g., “Bromo Suzuki coupling”, “N-Bn deprotection”, ...).

https://github.com/rxn4chemistry/rxnfp/blob/master/data/uspto_1k_TPL/individual_files/label_template.json
