### ISSUE TITLE
Simpletransformers version/set up

### ISSUE THREAD

**Issue by jpjanet** [rxn4chemistry/rxnfp#5]
Hi,

I am trying to get this repo working but I can't get the dependencies quite right. I took the following actions:
1.  pulled the repo from github
2.  created a blank cona env and installed rkdit (from -c rdkit) and tmap, as directed
3.  `pip install -e . to install rxnfp`

At this stage, I am able to run the little example:

```
from rxnfp.transformer_fingerprints import (
    RXNBERTFingerprintGenerator, get_default_model_and_tokenizer, generate_fingerprints
)

model, tokenizer = get_default_model_and_tokenizer()

rxnfp_generator = RXNBERTFingerprintGenerator(model, tokenizer)

example_rxn = "Nc1cccc2cnccc12.O=C(O)c1cc([N+](=O)[O-])c(Sc2c(Cl)cncc2Cl)s1>>O=C(Nc1cccc2cnccc12)c1cc([N+](=O)[O-])c(Sc2c(Cl)cncc2Cl)s1"

fp = rxnfp_generator.convert(example_rxn)
```

correctly and obtain the expected output. Next, I tried to run some of the nice example notebooks, but I run into an unmet requirement for simpleransformers, e.g.

`from rxnfp.models import SmilesClassificationModel`

results in 

```

ModuleNotFoundError                       Traceback (most recent call last)
LOCALPATH/rxnfp/rxnfp/models.py in <module>
     31 try:
---> 32     import simpletransformers
     33     logger.warning("This extension has only been tested with simpletransformers==0.34.4 and transformers==2.11.0")

ModuleNotFoundError: No module named 'simpletransformers'

```
I tried to install simpletransformers (from this [repo](https://github.com/ThilinaRajapakse/simpletransformers)) with 

`pip install simpletransformers`
 
which reveals the inconsistent dependency:

```
  Attempting uninstall: transformers
    Found existing installation: transformers 3.5.1
    Uninstalling transformers-3.5.1:
      Successfully uninstalled transformers-3.5.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rxnfp 0.0.8 requires transformers<4,>=2.5.1, but you have transformers 4.1.1 which is incompatible.
```

The latest version of simpletransformers [explicitly requires transformers >= 4.0.0 ](https://github.com/ThilinaRajapakse/simpletransformers/blob/master/setup.py). I tried ignoring the requirement and forcing transformers back to 3.5.1 but I got more errors.  I also tried with transformers 4.0.0 but I got errors about trying to call .squeeze() on string variables.

Is there a specific version of simpletransformers I should use?

I am running centos 7.

Thanks for any advice!

**Comment by pschwllr** [comment]
Hi, 

I should have better placed the warning (`"This extension has only been tested with simpletransformers==0.34.4 and transformers==2.11.0"`). 

Can you try if `simpletransformers==0.34.4` and `transformers==2.11.0` works for you?

Hugginface is updating too fast, it is hard to keep up :). The next `rxnfp` version will support transformers `>=4.0.0` but there were some breaking changes so I had to restrict it to `<4`.

**Comment by jpjanet** [comment]
Thanks, works now!

**Comment by Rojina99** [comment]
@pschwllr, I am wondering if these requirements have been updated i.e simpletransformers==0.34.4 and transformers==2.11.0 to transformers >=4.0.0, as you mentioned. I am unable to run this script due to version incompatibility (https://github.com/rxn4chemistry/rxnfp/blob/master/nbs/09_fine_tune_bert_on_uspto_1k_tpl.ipynb), so I wanted to confirm if these requirements have been updated. Because I can see in setup file https://github.com/rxn4chemistry/rxnfp/blob/master/settings.ini the version of transformer now is >=4.5.0. It would be really helpful if you could confirm it.
